### PR TITLE
 [package] [kernel-osmc] Add patch for em28xx chip support

### PR DESCRIPTION
**Pull request by hevvieevvie**
Kernel patch to support the Hauppauge WinTV-dualHD TV tuner card

### CODE REVIEW

**Comment by samnazarko** [comment]
It seems that this problem affects other platforms on 4.4. It would be good if you could:

* Rename the commit to [package] [kernel-osmc] to follow proper naming conventions
* Add the patch for atv and vero1 targets.

You can do this by adding an additional commit to add the new targets, then running git rebase -i HEAD~2. Put 'fixup' on the most recent commit and 'reword' on the original commit so that you can rename it. Then git push --force +master

**Comment by hevvieevvie** [comment]
Hi Sam, I think it's done. Please let me know if it's not right?

**Comment by samnazarko** [comment]
Looks good -- you just need to squash this down now (use fixup) on git rebase.

**Comment by hevvieevvie** [comment]
Should be all done Sam. Thanks.

**Comment by samnazarko** [comment]
Hi

The patch doesn't apply cleanly to the Vero 2 target, but this uses an older kernel, so I've adapted the PR and it's good to cherry-pick. This will be included in OSMC's August update.

Thanks!

**Comment by hevvieevvie** [comment]
Excellent. Glad to be of assistance. Thanks Sam.

**Pull request closed without merging**
