### PR TITLE
Package for Kodi Screen Reader

### PR DESCRIPTION
**Pull request by leonardder**
Hi,

Based on the proposal in #250, this pull request contains the mediacenter-screenreader-osmc package. It packages the [Kodi Screen Reader](http://ruuk.github.io/service.xbmc.tts/) by @ruuk. Currently, version 1.0.6beta1 is used, as that version contains certain fixes which allow the addon to run from special://xbmc/addons/service.xbmc.tts.

As soon as this package is installed and Kodi is started, the screen reader addon runs, installs its key map to allow running the screen reader with f12, and than disables itself. This way, it is perfectly suitable to be added to the default OSMC distribution. People who do not want to run a screen reader simply shouldn't start it. Simlar to this, VoiceOver is included on both Apple Mac OS X and iOS.

A known issue in this beta version of the addon: when switching from the addon installed in special://home to special://xbmc, the addon sounds aren't played correctly. This will be fixed in 1.06 final, probably in time for the next OSMC release.

Please let me know what you all think and how I can help you guys further in making OSMC a media center OS which is accessible to the blind and visually impaired by default.

Regards,
Leonard

### CODE REVIEW

**Comment by samnazarko** [comment]
Thanks, I'll review this in the coming days and let you know my thoughts.

**Comment by leonardder** [comment]
Just updated my screenreader branch to the latest version of the kodi screen reader addon. This one should fix issues with sounds not playing.
Would be great if this could be merged into master and a package could be build for the debian repositories, so installing is just a single apt-get install mediacenter-screenreader-osmc. Integrating the addon in OSMC itself could be a second step, but is certainly not required for this pull request imo.

**Comment by leonardder** [comment]
@samnazarko: Are you still considering reviewing this? If so, I should update to the most recent version first.

**Comment by samnazarko** [comment]
If you give it a bump I'll get it in our App Store. I'm wondering how popular Kodi / OSMC is currently with the visually impaired.

**Pull request closed without merging**
