### PR TITLE
[package] [kernel-osmc] Upgraded rbp kernel to 4.9.53

### PR DESCRIPTION
**Pull request by MrTschi**

### CODE REVIEW

**Comment by MrTschi** [comment]
Proof that it works: https://picload.org/view/dgpdgoca/61m1cojqsybzt2uhtkhjg.jpg.html

**Comment by samnazarko** [comment]
Hi

Thanks for this.  I suspect the next kernel update for Pi will be 4.14.
If there are any improvements that you need / want for 4.9, then please let me know. At this stage I'd prefer to cherry-pick individual commits for now

**Comment by MrTschi** [comment]
Hi

this is the main reason for the upgrade:
https://github.com/raspberrypi/linux/issues/2134

**Comment by samnazarko** [comment]
I already backported that in 975c40e3ebc1c7041bcec7a4825819cff5022d45

You removed the backport when you updated to 4.29.53

**Comment by MrTschi** [comment]
With current osmc kernel I got a lot of artefacts in live tv using a usb dvb-s2 card. Its gone since the kernel upgrade. Any Ideas?

**Comment by samnazarko** [comment]
It's only in staging / master
Not in release yet.

Did you try building OSMC kernel as-is and installing?

**Comment by MrTschi** [comment]
Ah ok, no I didn't try building master of osmc-kernel package. I have that issue with artefacts since osmc upgraded to 4.9 (half a year?), so I thought this is never going to get fixed :D

**Comment by samnazarko** [comment]
The issue was only reported at the end of July, but I do believe it was present for some time in 4.9
It will be addressed in the next OSMC update.

**Comment by MrTschi** [comment]
Could you please send me the link to the issue?

**Comment by samnazarko** [comment]
A kernel upgrade isn't feared; but you are bumping untested code and using a screenshot of Kodi's menu to state that it works. There could very well be regressions. 4.9 can now be considered EOL for us and we are waiting for 4.14 for RBP. 

The issue I am referring to is the one you mentioned a couple of comments above. It was only opened on 27th July and a fix was only found in the middle of September.

**Comment by MrTschi** [comment]
Ok thank you sam.
I'll test it as far as the new release of osmc is out ;) Till then I'll use the 4.9.53 kernel.

**Comment by MrTschi** [comment]
@samnazarko the release 2017.10-1 didn't fix the DVB-S2 continuity errors for me
`tvh_1    | 2017-11-17 14:06:01.643 [WARNING] TS: Astra/10832.25H/VOX HD: H264 @ #511 Continuity counter error (total 1)`
`tvh_1    | 2017-11-17 14:13:07.648 [WARNING] TS: Astra/10832.25H/VOX HD: H264 @ #511 Continuity counter error (total 2)`
`tvh_1    | 2017-11-17 14:20:55.510 [WARNING] TS: Astra/10832.25H/VOX HD: H264 @ #511 Continuity counter error (total 3)`
...

**Comment by samnazarko** [comment]
Thanks for the feedback.
Can you try the  TVHeadend update here: https://discourse.osmc.tv/t/testing-tvheadend-4-2-4/39949

**Comment by MrTschi** [comment]
Running on tvheadend "4.2.4-41~g1c9944bb2" on "Linux version 4.9.29-10-osmc"
Problem still occurs.

**Pull request closed without merging**
