### PR TITLE
[package] [kernel-osmc] Add proper Astrometa DVB-C tuner support

### PR DESCRIPTION
**Pull request by karower**
Watching live TV with the cheap Astrometa DVB-C tuner you will see artifacts after somer time at higher frequencies. This patch avoids those artifacts.
Found here: [https://tvheadend.org/boards/5/topics/22310?r=25348#message-25348](url)

### CODE REVIEW

**Comment by samnazarko** [comment]
Thanks for the PR. Did you build your kernel with this file name? I don't believe the patch would be applied at build time if named this way; so you may have experienced a placebo affect here.

Calling the patch rbp-032-fixup-astrometa-dvbc.patch may be more appropriate.

**Comment by karower** [comment]
No, sorry I forgot, I had named it rpb2-linux-999_r820t.patch

**Comment by karower** [comment]
I changed the name as suggested for pull request.

**Comment by samnazarko** [comment]
Can you squash this in to one commit and the commit message match the PR title?

**Comment by karower** [comment]
Don't know how to. Will have a look later at home.
Sorry for the inconvenience. It's my first time pull request.

**Comment by samnazarko** [comment]
I can just cherry-pick this if it's easier for you. Thanks for finding this and reporting it.

**Comment by samnazarko** [comment]
Closed as picking manually.

**Pull request closed without merging**
