### PR TITLE
[package][mediacenter-addon-osmc] Updates to all Python add-ons

### PR DESCRIPTION
**Pull request by anxdpanic**
- Python 2/3 & Kodi 18/19 compat.
- restructure modules
- refactor to use modules as kodi modules
- refactor to use osmccommon kodi module
- refactor for optimization
- remove python path modifications
- use My OSMC icons for module icons
- add license and license headers
- remove script.module.elementtree
- some localisation
- linting
- cosmetics

### CODE REVIEW

**Comment by Ch1llb0** [comment]
Just wondering, did you, by any chance, rework the module which were still using the old style to look like the network or update module?

**Comment by anxdpanic** [comment]
@Ch1llb0 I haven't made any UI related changes so far

**Comment by Ch1llb0** [comment]
Well, if you have time, maybe you can look at that as well? Would be great to get some consistency here 👍

**Comment by anxdpanic** [comment]
My skinning abilities/knowledge is quite limited. I'll take a look but it may be more productive for me to focus elsewhere-still related-.

**Comment by Ch1llb0** [comment]
Will have a look at it some time 👍

**Pull request merged**
