### PR TITLE
added support for: Dell Travel Remote NU-851

### PR DESCRIPTION
**Pull request by hhromic**
Hello,
Here is the PR with a lirc configuration file and an image to support the Dell Travel Remote NU-851 out-of-the-box in OSMC.

Cheers!
Hugo.

### CODE REVIEW

**Comment by hhromic** [comment]
I found out that lirc doesn't like spaces in remote names:

```lircd: WARNING: garbage after 'name' token in line 17 ignored```

...so I updated the PR. Make sure you merge the new commit as well. I also found that many of the existing remote configs have the same problem. If you want I can fix them and add another PR with this.

Cheers,
Hugo.

**Comment by samnazarko** [comment]
Squash these commits please

**Comment by hhromic** [comment]
Hi Sam,
Do you want me to create a PR with a single commit ?
Cheers

**Comment by samnazarko** [comment]
You can also just squash the existing two commits but if easier for you then create a new one

**Comment by hhromic** [comment]
Sorry I think I screwed the PR up.. I never tried to squash commits before. I'll create a new one, you can close this.

**Pull request closed without merging**
