### PR TITLE
Add Twofish cipher support

### PR DESCRIPTION
**Pull request by notapirate**
Since Twofish is well supported by LUKS and dm-crypt and as safe as AES, it should be available at least as module. Thank you.

### CODE REVIEW

**Comment by samnazarko** [comment]
Can you make this change to all config and squash?

**Comment by notapirate** [comment]
Forgive me but I'm not an github expert. What I could see so far is that I can make the change to all config files and make a seperate pull request for each of them.

**Comment by samnazarko** [comment]
Do them as separate commits and then fix up to meld them in to one

On 16 Jan 2016, at 15:55, notapirate <notifications@github.com<mailto:notifications@github.com>> wrote:


Forgive me but I'm not an github expert. What I could see so far is that I can make the change to all config files and make a seperate pull request for each of them.

-

**Comment by notapirate** [comment]
I changed all necessary files. The versions for ATV already has it as module and vero as build-in, so I changed the configs for pc, rbp1, rbp2 and vero2

**Comment by notapirate** [comment]
changed files in installer directory too

**Comment by notapirate** [comment]
If I missed a file, please tell me so. Otherwise I would appreciate if the changes could be merged with master branch, because right now I have to manually recompile the kernel after every kernel update to get the module, which I believe is quite unnecessary for such a small change... :)

**Comment by samnazarko** [comment]
Please squash the the commits and create a new PR for all platforms

**Comment by notapirate** [comment]
OK I squashed all changes to my master fork. Now I close this PR and create a new one from my master with the changes right? Sorry I'm still kinda new to this stuff

**Pull request closed without merging**
