### PR TITLE
Add 'supported_models' to NOOBS os.json files for newer NOOBs versions

### PR DESCRIPTION
**Pull request by matthuisman**

### CODE REVIEW

**Comment by samnazarko** [comment]
I'll check with the NOOBS maintainer if this should replace supported hex revisions entirely. We had a discussion about this last week but only briefly.

Sam

**Comment by matthuisman** [comment]
I think it would be best to have both for backwards compatibility with older NOOBs versions?

If you look at latest Raspbian os.json - they have both
http://downloads.raspberrypi.org/raspbian/os.json

**Comment by samnazarko** [comment]
Looks like it. I'll verify with the maintainer anyhow.

**Comment by matthuisman** [comment]
In saying that, the hex versions may then need updating.
Maybe the Pi3 is 2082 and that needs adding to os-pi2.json
Same with Zero hex version on the os-pi1.json

**Comment by samnazarko** [comment]
See http://downloads.raspberrypi.org/osmc_pi1/os.json for an example of what we're doing currently. This was updated by the NOOBS maintainer.

**Comment by samnazarko** [comment]
Addressed in 14f710935d1b0a4e207a092add532df0308f1685

**Pull request closed without merging**
