### PR TITLE
[package] [connman-osmc] Upgrade to 1.33

### PR DESCRIPTION
**Pull request by ste-fan**
Delete obsolete (already incorporated) patches and update remaining patches.

ConnMan version 1.33 seems to be needed to work with WiFi band steering routers (which tell dual-band WiFi clients when to switch between two 2.4 GHz and 5 GHz APs with an identical SSID). According to [01.org](https://01.org/connman/blogs/pflykt/2016/connman-1.33) the band steering feature was added in that version.

After activating band steering in my router [1], my client [2] lost the WiFi connection after a while. Upgrading to ConnMan 1.33 fixed the issue.

[1] AVM FRITZ!Box 7490 (FRITZ!OS 06.80)
[2] Raspberry Pi 2 Model B Rev 1.1, Realtek Edimax AC600 USB (OSMC 2016.12-1)

### CODE REVIEW

**Comment by ste-fan** [comment]
Applies to OSMC 2017.02-1 as well.

**Comment by samnazarko** [comment]
Thanks for this PR. Please do not change authorship on patches. 

I think it should be possible to backport the band steering patch. I'm reluctant to bump to ConnMan 1.33 yet for a couple of reasons:

* You will need patch(es) for systemd or ConnMan master, or you will experience a delay in IP assignment when using DHCP.
* There are system changes, such as the use of symlinks for resolv.conf and a 'protected system mode'

We'd like to stick with the current version of ConnMan for a while as there are some improvements we want to make to this version.

**Comment by ste-fan** [comment]
OK. I used `git rebase` to automatically update the patches; that's how my authorship ended up in the files that did not supply any. I fixed the commit accordingly.

Concerning the backport of the band steering feature I opened a separate PR #351.

**Comment by samnazarko** [comment]
Use git am --reject and authorship is retained. 
Have you compiled your changes and are you happy with them? I'm happy to accept #350 and #351 and push them in to staging for some testing from our team.

**Comment by samnazarko** [comment]
Thanks for this patch.

**Pull request merged**
