### PR TITLE
issue 224 - moved pop-up message before downloading files.

### PR DESCRIPTION
**Pull request by Quimstr**

### CODE REVIEW

**Comment by samnazarko** [comment]
The description of the commit looks good, I think this was mentioned a while back but we forgot to do it. But looking at your code, it seems that your changes will not effect the downloading process.

Your commit ensures that the device is only unmounted post-dialog presentation. We want to unmount before asking the user if they wish to proceed because we want to ensure we're in a position to be able to write first; and we need to deal with things like AV software which might lock the device for scanning.

**Comment by Quimstr** [comment]
Well, yeah, I can see now, what I've done ; p
I'm gonna make it better soon.

So where do we want this pop-up exactly and do we want one of them? : ]

is popup after clicing 'next' button in license agreement ok, or should I move it after download starts?

**Comment by samnazarko** [comment]
I think the popup is fine where it is at the moment, but you could move it to before downloading the files, as long as the unmounting is done after downloading the files. We want to do any unmounting as late as possible so that there is a lower opportunity for something else (AV scanner etc) to grab the device again.

You should also prefix commits to this part of OSMC with [installer] [host]. 

If you're serious about cpntributing to the installers; we are redesigning the host (one that runs on the user's computer), and target (one that runs on the device and sets it up) installers. They will still be Qt based but they will get some much needed visual improvements and a code tidy-up. Let me know if this is something you'd like to work with.

**Comment by Quimstr** [comment]
I've been using osmc for some time now (great work btw) and I feel like I should give something back. Count me in ; )
Also I think I'd like better target installer, since I'm more of a linux guy.

**Comment by samnazarko** [comment]
That's great. I want to improve the target installer so that it is ready for PC (x64). There's a bit of work to do with that. I think we should also take the opportunity to bring it up to Qt 5 and make it look better as well.

If you have experience with Qt, that's a plus

**Comment by Quimstr** [comment]
I haven't been working with qt, but I know c/cpp. Nothing stops me from getting this experience now ;)

**Comment by Quimstr** [comment]
Do you want me to jump right into:
https://github.com/osmc/osmc/tree/master/installer/target/qt_target/qt_target_installer
and upgrade it to Qt 5?

**Comment by samnazarko** [comment]
Yes and no.

For the host installer itself, I'd like to make sure everything is working on the latest version of Qt 5. For some Linux distributions, we're still using Qt 4.x with some #ifdef hackery. Those distributions are getting old now, and we should be able to compile everything statically in the future anyway to avoid runtime dependency differences. The main benefit of Qt 5.x is HiDPI support, which is becoming more prevalent and is not properly supported by the OSMC host installer.

The target installer itself is slightly different. There don't seem to be any features or improvements as a result of moving to Qt 5, but there is a lot of work. If you have a look at the target installer, you will see the code can be easily shared across all devices, and to add a new device you just need a minimal kernel configuration and minimal buildroot configuration. Qt 5 deprecates QWS which means we would start having to include platform specific EGL libs, unless we used LinuxFB, which seems to be limited.

If you're serious about contributing, I'd suggest we have a chat and I can explain what we'd like to improve in the target installer. I think we could clean up the code a lot, and someone with C++ experience can help with that. We could also 'animate' the screen a little more, so that we can display slides, like NOOBS does to users when they are installing a new OS on the Raspberry Pi. The installer itself was written very quickly, converting a shell script to C++ (lots of system()) to provide some basic graphical output. It can be improved quite easily.

**Comment by Quimstr** [comment]
How exactly do you want to chat? : ]

**Comment by samnazarko** [comment]
Check your email.

**Pull request closed without merging**
