### PR TITLE
Md5 hash check for config txt

### PR DESCRIPTION
**Pull request by beRto-**
Compares config.txt before and after changes are made. If no changes (hashes match), user is not prompted for a reboot.

Notes:

1. Python indenting did not look quite right on GitHub version, so this needs to be checked
2. Have not run a full regression using a compiled code package (only testing the functions using a local test script)

### CODE REVIEW

**Comment by alistair-broomhead** [comment]
The reason why the indentation looks weird is that there's a mixture of tabs an spaces here - this is a big no-no as it can cause difficult to find issues (where one person's tab indentation is displayed differently to another's)

The community standard is to indent with 4 spaces, this file is predominantly indented with tabs, my advice would be to make sure that everything is correctly indented with tabs (to ensure everything is consistent) and then seen @samnazarko's point of view as to whether he wants these converted to spaces (which is at this point a simple `.replace('\t', '    ')` on the source code)

**Comment by alistair-broomhead** [comment]
Having read https://github.com/osmc/osmc/issues/266 I can see that tabs seem to be preferred. I can recommend [PyCharm](https://www.jetbrains.com/pycharm/) as an editor, the community edition is perfectly good for projects like this one, and is free. For testing under windows I would reccomend you make yourself aquainted with [Docker](https://docs.docker.com/engine/installation/windows/), which allows you to spin up a consistent and reproducible linux environment. Running a gui environment under a windows docker host my be tricky though, so you might alternatively want to use [Virtualbox](https://www.virtualbox.org/) to run a linux testing environment. The pros of virtualbox over docker are that it's easier to get started with, the cons are a lack of reproducibility, but there's a chance that setting up a good docker env under a linux vm may be easier than doing so on a windows host anyway. (I use linux myself so I can't test this assumption)

**Comment by DBMandrake** [comment]
Tabs is the indent style for Python in My OSMC so any pull requests submitted for My OSMC should use exclusively tabs for indent, so if there is a mixture of spaces and tabs in your pull request please clean this up so that they are all tabs.

**Comment by beRto-** [comment]
Thanks for all the feedback. Long story short, I deleted the my original fork and so I do not think I can update this commit without further confusing things. I will close this and resubmit with a version that is cleaned up for tabs etc. (I noticed OSMCsetting.py has been changed substantially since I made this pull request anyways, so it will be good to rebase.)

**Pull request closed without merging**
