### PR TITLE
Added Clock size for screensaver.digitalclock

### PR DESCRIPTION
**Pull request by vdb86**

### CODE REVIEW

**Comment by vdb86** [comment]
This was discussed with Sam, I pointed out that I had some users ask me to make screensaver.digitalclock compatible with skin.osmc.
My screensaver requires certain font sizes and relies on the skin to provide them.
I just added one font size which I needed.
Let me know if you have any questions.

**Comment by samnazarko** [comment]
Looks good, if you want to be complete, bump files/DEBIAN/control and change the version to 3.1.0-2 in another commit on this branch

**Comment by samnazarko** [comment]
Please put the two commits in one PR.

Sam

**Comment by vdb86** [comment]
All done!
I was looking into My OSMC menu in hopes I would be able to assist you with a redesign.
Unfortunately it's too advanced for me.
I'll keep looking, but at this point I'm drawing a blank.

**Comment by samnazarko** [comment]
Hi -- they are two separate PRs. It would be good if they were under one.

Re. My OSMC menu: we have plans to remove this from a radial menu to a standard list based one. This will be done by @KODeKarnage

**Comment by samnazarko** [comment]
If it's easier, I can cherry pick your commits and save you the hassle.

**Comment by vdb86** [comment]
I'm trying to figure out how to put it under one pull request.
If you're not in a hurry let me figure it out.
I'll have to learn this at some point, I guess better sooner than later.

**Comment by vdb86** [comment]
Alright, everything should be under patch-1 now!

**Comment by samnazarko** [comment]
Yep. Looks good. Will compile that now and push it to our staging repo. Thanks a lot!

**Comment by vdb86** [comment]
You're welcome!
I'll get the guys at Kodi to update my screensaver on official repository so users can enjoy it with your skin too.

**Comment by samnazarko** [comment]
Excellent -- keep us posted.

**Pull request merged**
