### PR TITLE
[package] [mediacenter-addon-osmc] Added support for Allo Boss DAC

### PR DESCRIPTION
**Pull request by git4jai**
Support for Allo Boss HiFi DAC

### CODE REVIEW

**Comment by samnazarko** [comment]
The commit needs the naming scheme, not the name of the PR.
You don't need to recreate the PR; just reword the commit and force push.

**Comment by samnazarko** [comment]
Squash the commits -- we don't need two; or I can just cherry-pick.

**Comment by git4jai** [comment]
Anything I missed? Pls let me know.

**Comment by samnazarko** [comment]
Looks good. I just didn't get a notification because of the force push.

**Comment by samnazarko** [comment]
This is now built and will be in the next update

**Comment by git4jai** [comment]
Thank you

**Pull request merged**
