### PR TITLE
[package] [kernel-osmc] Add zRAM support to rbp2

### PR DESCRIPTION
**Pull request by johnfocker**
Resolves osmc/osmc#246

### CODE REVIEW

**Comment by samnazarko** [comment]
This needs rebasing.

**Comment by radical-equanimity** [comment]
Hi Sam- when can we expect zram to become available to existing OSMC installations?

**Comment by samnazarko** [comment]
It’s already in the latest update

Sent from a mobile device, so please excuse the brevity of this reply

On 20 Mar 2018, at 19:07, Daniel Nowak <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Sam- when can we expect zram to become available to existing OSMC installations?

**Comment by radical-equanimity** [comment]
Thank you, I needed to do upgrade twice to see it- zram is working for me now

**Pull request closed without merging**
