### PR TITLE
[installer] More Vero-centric prompts

### PR DESCRIPTION
**Pull request by graham8**
May help users understand the install options better.

### CODE REVIEW

**Comment by samnazarko** [comment]
Instead, it might be better for us to not show this screen if the target device is Vero 2 or Vero 4K / 4K +

**Comment by graham8** [comment]
Even better, yes.

**Comment by samnazarko** [comment]
Should be superseded by: https://github.com/osmc/osmc/commit/b634abaf9927bd010345a3976cb7416cc961809c

Are you happy with this?

**Comment by graham8** [comment]
Still recommend the revised wording on the other dialogs.

**Comment by samnazarko** [comment]
You're right -- it makes more sense.

**Pull request merged**
