### PR TITLE
AppleWhite Remote: KEY_MENU-> KEY_ESC

### PR DESCRIPTION
**Pull request by M-Pan**
Modifying Apple Remote to work as before the Jarvis Update.

### CODE REVIEW

**Comment by DBMandrake** [comment]
Are you sure KEY_ESC is the correct fix ? Can you please try KEY_TITLE instead and test the functionality of the button in all locations within Kodi ?

**Comment by M-Pan** [comment]
I was going off of what Smurphy said in https://discourse.osmc.tv/t/apple-remote-silver-menu-button-does-not-work-anymore-as-back-button-as-before-osmcs-february-update/13475/19

He said KEY_MENU --> KEY_ESC worked in his case so that was what I was going off of. I'll try KEY_MENU --> KEY_TITLE with my ATI.

**Comment by M-Pan** [comment]
KEY_TITLE didn't work with my ATI. The atilibusb-lircd.conf already had a line for KEY_TITLE but I don't know which button that is supposed to point to,

I'm closing this for now so I can go to bed since it's nearly 5am.

**Comment by DBMandrake** [comment]
This is now fixed.

https://github.com/osmc/osmc/commit/77ad6c0a113771485c2f3ab4762b033c8723aad2

**Pull request closed without merging**
