### PR TITLE
[package] [kernel-osmc] RBP: add BBR support

### PR DESCRIPTION
**Pull request by jauderho**
CONFIG_TCP_CONG_ADVANCED=y
CONFIG_TCP_CONG_BBR=m
CONFIG_NET_SCH_FQ=m

### CODE REVIEW

**Comment by samnazarko** [comment]
Just to confirm: this doesn't change the defaults?
Would also be good if you could show some benchmarks or information that shows the benefits of this. 

Can you also change the commit message to [package] [kernel-osmc] RBP: add BBR support. You can force push and the PR will be updated.

**Comment by samnazarko** [comment]
Squash it please.

**Comment by jauderho** [comment]
I think I did this correctly. Did a force push but it does not seem as if the PR updated with the new message.

As for BBR details, here's the research paper from Google: https://research.google.com/pubs/pub45646.html

**Comment by samnazarko** [comment]
There are 5 commits now. They need to be squashed to one for us to merge.

**Comment by samnazarko** [comment]
Paper is nice, but a Phoronix benchmark or something similar would be a nice way to see the practicality of this.

**Comment by jauderho** [comment]
I'm not quite sure how to squash this correctly into one commit. Should I just spin up a new PR instead?

The benchmark I posted above was just done on my systems.

**Comment by samnazarko** [comment]
Rebase then force push.

>The benchmark I posted above was just done on my systems.

What did you test this on?

I'd be more interested in seeing the benefits of this on two RBP devices. There are two things that make this platform specific:

* Ethernet connected via USB
* The congestion algorithm may be beneficial under high traffic, but tax the ARM more. In which case, any benefits may be negated.

**Comment by jauderho** [comment]
I do not have spare RBPs lying around that I can test on right now. 

However, there is some anecdotal evidence here: https://github.com/raspberrypi/linux/issues/1784#issuecomment-274258501

raspberrypi/linux#1784

**Comment by samnazarko** [comment]
Understood. Thanks for the link.
I'm happy to merge this, as it will not change the default.

I'll keep an eye on this and if it does improve things under a typical OSMC workload, then I'll make it the default.

**Comment by samnazarko** [comment]
It shows two commits now, so you just need to remove your merge commit. If you're having trouble with this I can just cherry-pick it for you.

**Comment by jauderho** [comment]
Please do cherry-pick it. I don't use git on a regular basis.

**Comment by samnazarko** [comment]
I'll sort this out manually.

Kernel builds will be in staging in a few hours.

**Pull request closed without merging**
