### PR TITLE
[package] [kernel-osmc] Add Twofish cipher support

### PR DESCRIPTION
**Pull request by notapirate**
Adds Twofish kernel module support to all devices that don't have Twofish built-in.

### CODE REVIEW

**Comment by samnazarko** [comment]
Hi

You have missed the Vero 1 and AppleTV platforms.
Is there a reason this needs to be included in the installer kernels? We try and keep them minimal as little functionality is needed.

**Comment by notapirate** [comment]
Hi,
Vero1 has it already built-in and Apple-TV as module, so no changes needed.
There is no apparent reason the installer needs it, I just wanted to be thorough :)

**Comment by notapirate** [comment]
Shall I do it again without the installer patches?

**Comment by samnazarko** [comment]
Yes; and please add it for ATV and Vero 1.

You don't need to make a new pull request. See the section about 'fixup': https://osmc.tv/wiki/development/contributing-to-osmc/. You can then do git push --force origin +twofish_patch to push an updated topic branch.

**Comment by samnazarko** [comment]
Thanks for clarifying re ATV and V1.

**Comment by notapirate** [comment]
I'm sorry I did not understand; do you want me to create patches for ATV and V1, and if so, what exactly shall I patch there?

**Comment by samnazarko** [comment]
If V1 and ATV already have everything included, then no need to change anything there.

Comment re-fixup was for dropping the installer patches.

**Comment by notapirate** [comment]
OK thanks for clearing that up :)

**Comment by notapirate** [comment]
Well then, that wasn't the straight path but now I think it's done

**Comment by samnazarko** [comment]
Thanks. Looks good. I picked the patch manually.

Jenkins is building these kernels now. This means that in a few hours, the following commands will let you (hopefully) update to a kernel with this module included. I'd appreciate it if you could test:

You can modify /etc/apt/sources.list and add

deb http://apt.osmc.tv jessie-devel main

and apt-get update && apt-get dist-upgrade to check.

**Comment by notapirate** [comment]
I just tested the development version and it works just like it should.

**Comment by samnazarko** [comment]
Thanks for confirming


Sent from a mobile device, so please excuse the brevity of this reply

On 22 Nov 2016, at 18:00, notapirate <notifications@github.com<mailto:notifications@github.com>> wrote:


I just tested the development version and it works just like it should.

-

**Pull request closed without merging**
