### PR TITLE
Fixes for installer: El capitan device searching and QT fix

### PR DESCRIPTION
**Pull request by epichub**
not sure about the changes to "installer/host/qt_host_installer/wifinetworksetup.ui", I needed that to compile against my qt 4.8.6. But the other changes had to be made for the installer to find my SD card, "Ejectable" is not used anymore.

### CODE REVIEW

**Comment by epichub** [comment]
should fix issue #194

**Comment by samnazarko** [comment]
* Can you remove the binary icons generated?
* Can you show me the error if you don't change wifinetworksetup.ui

Sam

CC @srmo

**Comment by epichub** [comment]
Ok staging another commit with the icon removed (dunno why it was there, seems that the makefile deletes it after compiling successfully). 
The error message i regarding the setInputMethodHints was the following:
```
./ui_wifinetworksetup.h:125:111: error: no member named 'ImhSensitiveData' in namespace 'Qt'
        keylineEdit->setInputMethodHints(Qt::ImhHiddenText|Qt::ImhNoAutoUppercase|Qt::ImhNoPredictiveText|Qt::ImhSensitiveData);
                                                                                                          ~~~~^
```

**Comment by samnazarko** [comment]
Hi

Thanks for getting back to me.

The error was probably a Qt4 -> Qt5 thing. I'll wait until the end of the month when I can get access to a Qt 5 Mac and then I'll take the commit then if it's all good.

Sam

**Comment by srmo** [comment]
Grr. Didn't get the notification for #194 . On the other hand, don't have El Capitain available.
Just as a remainder: ImhSensitiveData is a nice thing to have. It may help avoiding security concerns from users.

**Comment by srmo** [comment]
fixes #194

**Pull request closed without merging**
