### PR TITLE
[package] [mediacenter-addon-osmc] fixup backup verification to smb://

### PR DESCRIPTION
**Pull request by LewpyUK**
[package] [mediacenter-addon-osmc] fixup backup verification to smb://

### CODE REVIEW

**Comment by anxdpanic** [comment]
Thanks @LewisBerrie  👍 
Can you also change the isfile instance before and after this as well. xbmcvfs.exists will be safe for those instances as well.

**Comment by LewisBerrie** [comment]
no problem @anxdpanic 👍
The two other instances have been changed as well.

**Review by anxdpanic — APPROVED** [review]
Thank you again 👍

**Comment by samnazarko** [comment]
Cheers. This is now in staging.

**Pull request merged**
